sonar.sources=src,cli
sonar.tests=tests
sonar.test.inclusions=tests/**/*.ts
sonar.exclusions=coverage/**,dist/**,reports/**
sonar.javascript.lcov.reportPaths=reports/lcov.info
sonar.sourceEncoding=UTF-8
